<?php

namespace app\validation;


use app\model\user_config;
use app\model\user_friend;

class add_friend extends \pms\Validation
{

    protected function initialize()
    {
        # 验证这个人是否允许直接加好友
        $this->add_where('user_id2', [
            'model' => user_config::class,
            'wheres' => [
                'user_id' => 'user_id2',
                'config_name' => 'config_name',
                'config_value' => 'config_value'
            ],
            'message' => 'not_allow'
        ]);
        # 验证是否已经是好友
        $this->add_where('user_id', [
            'model' => user_friend::class,
            'wheres' => [
                'user_id' => 'user_id',
                'user_id2' => 'user_id2'
            ],
            'negation' => true,
            'message' => 'already_friend'
        ]);
        return parent::initialize(); // TODO: Change the autogenerated stub
    }
}