<?php

namespace logic\user\validation;

use logic\user\model\user_friend;
use logic\user\model\user_friend_apply;
use logic\user\validator\user_exist;

/**
 *
 * Class add_apply
 * @package logic\user\validation
 */
class add_apply extends \pms\Validation
{

    protected function initialize()
    {
        # 用户验证
        $this->add_Validator('user_id', [
            'name' => user_exist::class,
            'message' => 'user_exist'
        ]);
        $this->add_Validator('user_id2', [
            'name' => user_exist::class,
            'message' => 'user_exist'
        ]);
        # 自己不能申请自己
        $this->add_NoEqual('user_id', [
            'with' => 'user_id2',
            'message' => 'me2me'
        ]);
        # reason 验证内容
        $this->add_stringLength('reason', [
            'meaasge' => 'stringLength',
            'min' => 0,
            'max' => 20
        ]);
        # 重复验证
        $this->add_where('user_id', [
            'model' => user_friend_apply::class,
            'negation' => true,
            'message' => 'addfrapcunzai',
            'wheres' => [
                'user_id' => 'user_id',
                'user_id2' => 'user_id2',
                'status' => 'status'
            ]
        ]);
        # 好友验证
        $this->add_where('user_id', [
            'model' => user_friend::class,
            'negation' => true,
            'message' => 'friend',
            'wheres' => [
                'user_id' => 'user_id',
                'user_id2' => 'user_id2'
            ]
        ]);

        return parent::initialize(); // TODO: Change the autogenerated stub
    }
}