<?php


namespace app\validation;

use logic\Common\validator\area;
use app\validator\user_exist;

/**
 * 用户信息验证
 * Class edit_info
 * @package app\validation
 */
class edit_info extends \pms\CoreValidation
{
    protected function initialize()
    {
        # 验证user_id
        $this->add_Validator('user_id', [
            'name' => user_exist::class,
            'message' => ''
        ]);
        #  gender 性别
        $this->add_in('gender', [
            'domain' => [
                2, 1, -1
            ],
            'message' => 'gender'
        ]);
        # birthday 生日
        $this->add_date('birthday', [
            'format' => 'Y-m-d',
            'message' => 'date'
        ]);
        #  personalized 个性签名
        $this->add_stringLength('personalized', [
            'min' => 0,
            'max' => 50,
            'message' => 'stringLength'
        ]);
        # area
        $this->add_Validator('area', [
            'name' => area::class,
            'message' => 'area'
        ]);

        return parent::initialize(); // TODO: Change the autogenerated stub
    }

}