<?php

namespace app\validation;

use app\validator\user_exist;

/**
 * 邮箱验证
 * Class EmailCaptcha
 * @package app\validation
 */
class EmailCaptcha extends \pms\Validation
{

    protected function initialize()
    {
        # 验证用户
        # 验证邮箱
        $this->add_email('email', [
            'message' => 'email'
        ]);

        return parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function beforeValidation1($data)
    {
        # 验证邮箱存在
        $this->add_where('email',[
            'wheres'=>[
                'email'=>'email',
                'status'=>'status1'
            ],
            'model'=>\app\model\user_email::class,
            'message'=>'email1'
        ]);
    }
}