<?php

namespace app\validation;

use logic\Attachment\Validator\picValidator;
use app\validator\Realauth_submit;
use app\validator\user_exist;

class Realauth extends \pms\Validation
{

    protected function initialize()
    {
        # 用户是否存在
        $this->add_Validator('user_id', [
            'name' => user_exist::class,
            'message' => 'user_exist'
        ]);
        # 数据是否允许修改
        $this->add_Validator('user_id', [
            'name' => Realauth_submit::class,
            'message' => 'realauth_submit'
        ]);
        # 验证真实姓名
        $this->add_stringLength('name', [
            'min' => 2,
            'max' => 30,
            'message' => 'stringLength'
        ]);
        # 验证身份证号码
        $this->add_stringLength('id_card', [
            'min' => 18,
            'max' => 18,
            'message' => 'stringLength'
        ]);
        # 验证图片 麻蛋的,好麻烦,有空再写吧

        return parent::initialize(); // TODO: Change the autogenerated stub
    }
}