<?php

namespace app\validation;

use app\model\user_qq;
use app\validator\user_exist;

/**
 * QQ关联验证
 * Class relevance_qq
 * @package app\validation
 */
class relevance_qq extends \pms\Validation
{
    protected function initialize()
    {
        # 验证用户
        $this->add_Validator('user_id', [
            'name' => user_exist::class
        ]);
        # 验证openid
        $this->add_where('openid', [
            'model' => user_qq::class,
            'wheres' => [
                'openid' => 'openid'
            ],
            'message' => 'qq_ex',
            'negation' => true
        ]);

        return parent::initialize(); // TODO: Change the autogenerated stub
    }

}