<?php
/**
 * Created by PhpStorm.
 * User: Dongasai
 * Date: 2017/11/7
 * Time: 17:13
 */

namespace app\validation;


use app\validator\user_exist;

class user_message extends \pms\CoreValidation
{
    protected function initialize()
    {
        # 目标用户
        $this->add_Validator('to_uid', [
            'name' => user_exist::class,
            'message' => 'exist'
        ]);
        return parent::initialize(); // TODO: Change the autogenerated stub
    }

}