<?php

namespace app\filterTool;

use pms\FilterTool\FilterTool;

class Demo extends FilterTool
{

    protected function initialize()
    {
        $this->_Rules[] = ['title', 'string'];
        $this->_Rules[] = ['user_id', 'int'];
        $this->_Rules[] = ['category_id', 'int'];
        $this->_Rules[] = ['description', 'string'];
        $this->_Rules[] = ['content', 'int'];
        $this->_Rules[] = ['view', 'int'];
        $this->_Rules[] = ['level', 'int'];
        $this->_Rules[] = ['can_reply', 'int'];
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}