<?php

namespace app\filterTool;

use pms\FilterTool\FilterTool;

/**
 * 多服务协同注册的过滤工具
 * Class Regs
 * @package app\filterTool
 */
class Regs extends FilterTool
{

    protected function initialize()
    {
        $this->_Rules[] = ['username', 'string'];
        $this->_Rules[] = ['password', 'string'];
        $this->_Rules[] = ['password2', 'string'];
        $this->_Rules[] = ['email', 'string'];
        $this->_Rules[] = ['nickname', 'string'];
        #
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}