<?php

namespace app\controller;

use app\Controller;


/**
 * 用户信息控制器 Info
 * Class InfoController
 * @package app\controller
 */
class Info extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 修改用户信息
     *
     */
    public function edit()
    {

        $data=$this->getData();
        $service = new \app\logic\Info();
        $re = $service->edit($this->user_id, $data);
        return $this->send($re);
    }

    /**
     * 用户信息
     * @return \Phalcon\Http\Response|\Phalcon\Http\ResponseInterface
     */
    public function info()
    {
        $service = new \app\logic\Info();
        $re = $service->info_user($this->user_id);
        var_dump($re);
        return $this->send($re);
    }

    public function p_info()
    {
        $user_id = $this->request->get('user_id', 'int', 0);
        $service = new \app\logic\Info();
        $re = $service->info_user($user_id);
        return $this->send($re);
    }

}