<?php

namespace app\controller;

use app\Controller;

/**
 * 消息 message
 * Class MessageController
 * @package app\controller
 * @property \logic\user\Message $MessageService
 */
class Message extends Controller
{
    public function initialize()
    {
        parent::initialize(); //TODO: Change the autogenerated stub
        $this->di->setShared('MessageService', function () {
            return new  \logic\user\Message();
        });
    }

    /**
     * 设置消息为已读
     */
    public function read()
    {
        $p = [
            'id' => ['get', 'id', 'int', 0]
        ];
        $data = $this->getData($p);
        $data['user_id'] = $this->user_id;
        $re = $this->MessageService->read($data);
        return $this->restful_return($re);

    }

    /**
     * 站内信列表
     * @return \Phalcon\Http\Response|\Phalcon\Http\ResponseInterface
     */
    public function list4user()
    {
        $type = $this->request->get('type', 'string', 'to');
        $page = $this->request->get('p', 'int', 1);
        $is_read = $this->request->get('is_read', 'int', -1);

        $re = $this->MessageService->list4user($this->user_id, $type, $is_read, $page);
        return $this->restful_return($re);
    }

    /**
     * 站内信详情
     * @return \Phalcon\Http\Response|\Phalcon\Http\ResponseInterface
     */
    public function info()
    {
        $id = $this->request->get('id', 'int', 0);
        $re = $this->MessageService->info4user($this->user_id, $id);
        return $this->restful_return($re);
    }

    /**
     * 发送站内信
     */
    public function send()
    {
        $p = [
            'to_user_id' => ['post', 'to_user_id', 'int', 1],
            'title' => ['post', 'title', 'string', ''],
            'content' => ['post', 'content', 'string', ''],
        ];
        $data = $this->getData($p);
        $data['user_id'] = $this->user_id;
        $re = $this->MessageService->send($this->user_id, $data['to_user_id'], $data['title'], $data['content']);
        return $this->restful_return($re);
    }
}