<?php

namespace app\controller;

use app\Controller;

/**
 * 消息 message
 * Class MessageController
 * @package app\controller
 * @property \app\logic\Message $MessageService
 */
class Message extends Controller
{
    public function initialize()
    {
        parent::initialize(); //TODO: Change the autogenerated stub
        $this->di->setShared('MessageService', function () {
            return new  \app\logic\Message();
        });
    }

    /**
     * 设置消息为已读
     */
    public function read()
    {

        $data = $this->getData('id',0);
        $data['user_id'] = $this->user_id;
        $re = $this->MessageService->read($data);
        return $this->send($re);

    }

    /**
     * 站内信列表
     * @return \Phalcon\Http\Response|\Phalcon\Http\ResponseInterface
     */
    public function list4user()
    {
        $type = $this->getData('type', 'string', 'to');
        $page = $this->getData('p', 'int', 1);
        $is_read = $this->getData('is_read', 'int', -1);
        $re = $this->MessageService->list4user($this->user_id, $type, $is_read, $page);
        return $this->send($re);
    }

    /**
     * 站内信详情
     * @return \Phalcon\Http\Response|\Phalcon\Http\ResponseInterface
     */
    public function info()
    {
        $id = $this->getData('id', 'int', 0);
        $re = $this->MessageService->info4user($this->user_id, $id);
        return $this->send($re);
    }

    /**
     * 发送站内信
     */
    public function send()
    {
        $to_user_id = $this->getData('to_user_id');
        $title = $this->getData('title');
        $content = $this->getData('content');

        $data['user_id'] = $this->user_id;
        $re = $this->MessageService->send($this->user_id, $to_user_id, $title, $content);
        return $this->send($re);
    }
}