<?php

namespace app\controller;

use app\Controller;

/**
 * 用户标签控制器
 * Class TagController
 * @package app\controller
 */
class Tag extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    /**
     * 进行标签关联
     */
    public function relation()
    {
        $pa = [
            're_id' => ['post', 're_id', 'int', 0],
            'title' => ['post', 'tag_title', null, []],
            'type' => ['post', 'type', 'string', '']
        ];
        $data = $this->getData($pa);
        $data['user_id'] = $this->user_id;
        $Tag = new \logic\user\Tag();
        $re = $Tag->relation($data);
        return $this->send($re);
    }


}