<?php

namespace app\controller;

use app\Controller;


/**
 * 电话相关的控制器
 * Class InfoController
 * @package app\controller
 */
class Tel extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * tet的手机验证码 ttc的新的手机验证码
     */
    public function edit_tel()
    {
        $data = $this->getData([
            'old_tel' => ['post', 'old_tel', 'string', ''],
            'captcha' => ['post', 'captcha', 'string', ''],
            'new_tel' => ['post', 'new_tel', 'string', ''],
            'new_captcha' => ['post', 'new_captcha', 'string', ''],
        ]);
        $telService = new \logic\user\Tel();
        $re = $telService->edit_tel($this->user_id, $data);
        return $this->restful_return($re);
    }


    /**
     * 手机信息
     */
    public function info()
    {
        $telService = new \logic\user\Tel();
        $re = $telService->info4user($this->user_id);
        return $this->restful_return($re);
    }

    /**
     * ttc的手机验证码
     */
    public function tel_captcha()
    {
        $tel = $this->request->get('tel', 'string', '');
        $captcha = $this->request->get('captcha', 'string', '');
        $telService = new \logic\user\Tel();
        $re = $telService->tel_captcha($this->user_id, $tel, $captcha);
        return $this->restful_return($re);
    }


}